// ============================================================================
// Valeria+ · El arte del ejercicio, en píxel art voxel 3D de 24×24
//
// FUENTE ÚNICA de los 66 pictogramas y los 9 glifos de insignia en estilo
// voxel isométrico infantil original. De aquí los copia el firmware de Lúa
// (lua-firmware/tools/build-art.js), igual que ya copia el sprite de la gata
// y la tabla de opcodes.
//
// El ORDEN de PICTO_KEYS es de por vida: el índice es lo que viaja por BLE en
// PICTO(i), así que meter uno en medio le cambia la ficha a todos los aparatos
// ya flasheados. Añadir al final es seguro; reordenar, nunca.
// ============================================================================

/** Paleta ampliada de colores voxel. El carácter '.' es fondo y no se pinta. */
export const PIXEL_PALETTE: Record<string, string> = {
  '#': '#181a20', // contorno tinta
  k: '#000000',   w: '#ffffff',   g: '#c5ccd6',   G: '#68707e',
  r: '#e62828',   R: '#911212',   o: '#ff851b',   m: '#ffdc00',
  M: '#fff677',   v: '#2ecc40',   V: '#1b7a2b',   t: '#00c4be',
  a: '#2f6fd0',   A: '#143a7a',   b: '#9b51e0',   B: '#5a208a',
  n: '#8b5a2b',   N: '#4a2c11',   q: '#fcedc7',   p: '#fca070',
  // Colores voxel ampliados para profundidad 3D
  c: '#a5f3fc',   // Cyan hielo / Luz de agua
  C: '#1e3a8a',   // Azul marino sombra
  T: '#007a78',   // Turquesa sombra
  O: '#c2410c',   // Naranja terracota sombra
  Y: '#d97706',   // Ámbar / Oro sombra
  P: '#f472b6',   // Rosa suave / Rubor
  h: '#fffbeb',   // Blanco marfil / Luz cálida
  s: '#e2e8f0',   // Plata / Gris claro luz
  S: '#334155',   // Pizarra oscura sombra
  l: '#84cc16',   // Verde lima / Brote luz
  d: '#c89666',   // Madera clara / Galleta / Masa
  D: '#38220f',   // Madera oscura sombra
};

export const PIXEL_SIDE = 24;

/** Los 66 pictogramas, EN ORDEN DE ÍNDICE. No reordenar. */
export const PICTO_KEYS = [
  'cepillo',                 // 0
  'tobogan',                 // 1
  'cubo',                    // 2
  'sierra',                  // 3
  'pelo',                    // 4
  'puente',                  // 5
  'numero-ocho',             // 6
  'numero-cero',             // 7
  'osito-grande',            // 8
  'osito-pequeno',           // 9
  'cuchara-limpia',          // 10
  'cuchara-sucia',           // 11
  'caja-abierta',            // 12
  'caja-cerrada',            // 13
  'vaso-frio',               // 14
  'vaso-caliente',           // 15
  'bombilla-encendida',      // 16
  'bombilla-apagada',        // 17
  'cesta-llena',             // 18
  'cesta-vacia',             // 19
  'coche-subiendo',          // 20
  'coche-bajando',           // 21
  'juguete-dentro',          // 22
  'juguete-fuera',           // 23
  'comer',                   // 24
  'dormir',                  // 25
  'soplar',                  // 26
  'banar',                   // 27
  'vestir',                  // 28
  'correr',                  // 29
  'nadar',                   // 30
  'parar',                   // 31
  'pajaro',                  // 32
  'jabon',                   // 33
  'vaso-leche',              // 34
  'cesta',                   // 35
  'cuchara',                 // 36
  'vaso',                    // 37
  'abrazo',                  // 38
  'rueda',                   // 39
  'manos-mojadas',           // 40
  'pluma',                   // 41
  'tubo',                    // 42
  'saltar',                  // 43
  'esponja',                 // 44
  'lana',                    // 45
  'lata',                    // 46
  'cuerda',                  // 47
  'papel',                   // 48
  'mano',                    // 49
  'mano-limpia',             // 50
  'palo',                    // 51
  'senalar',                 // 52
  'frio-cara',               // 53
  'torta',                   // 54
  'color-rojo',              // 55
  'color-azul',              // 56
  'color-amarillo',          // 57
  'color-verde',             // 58
  'color-morado',            // 59
  'color-marron',            // 60
  'pie',                     // 61
  'boca',                    // 62
  'ojo',                     // 63
  'rodilla',                 // 64
  'codo',                    // 65
] as const;

export type PictoKey = (typeof PICTO_KEYS)[number];

export const PICTOS: Record<PictoKey, readonly string[]> = {
  cepillo: [ // 0
    '........................',
    '.........#####..........',
    '........#hhhhh#.........',
    '.......#hwwwwws#........',
    '......#hwwwwwwws#.......',
    '.....#hccccccccT#.......',
    '.....#tctttttttT#.......',
    '.....#tTtttttttT#.......',
    '......#TTTTTTTT#........',
    '.......###TT###.........',
    '........#ttt#...........',
    '.......#tcttT#..........',
    '......#tctttT#..........',
    '.....#tcttttT#..........',
    '....#tctttttT#..........',
    '...#tcttttttT#..........',
    '..#tctttttttT#..........',
    '..#tcttttttTT#..........',
    '..#TTttttttT#...........',
    '...#TTTTTTT#............',
    '....#######.............',
    '........................',
    '........................',
    '........................',
  ],
  tobogan: [ // 1
    '........................',
    '.....####...............',
    '....#dddd#....###.......',
    '...#dddddd#..#MMM#......',
    '..#dd#DD#dd##mmmmM#.....',
    '..#d#D#D#d#r#MmmmmM#....',
    '..#d#D#D#drrr#MmmmmM#...',
    '..#d#D#D#drrrr#MmmmmM#..',
    '..#d#DD#ddrrrrr#MmmmmM#.',
    '..#dddddd#rrrrrr#MmmmmM#',
    '..#d#DD#d#Orrrrrr#Mmmmm#',
    '..#d#D#D#d#Orrrrrr#Mmm#.',
    '..#d#D#D#d##Orrrrrr##...',
    '..#d#D#D#d..#OOrrrrr#...',
    '..#d#DD#dd...#OOOrrr#...',
    '..#dddddd.....#OOOOr#...',
    '..#d####d......#OOOO#...',
    '..#d#..#d.......####....',
    '..#d#..#d...............',
    '..#D#..#D#..########....',
    '.#ll####ll##llllllll#...',
    '.#lvvvvvvvvvvvvvvvvv#...',
    '.#VVVVVVVVVVVVVVVVVV#...',
    '..##################....',
  ],
  cubo: [ // 2
    '........................',
    '.........######.........',
    '.......##ssssss##.......',
    '......#ss######ss#......',
    '.....#ss#......#ss#.....',
    '....#s#..........#s#....',
    '...#s#............#s#...',
    '...#s#...######...#s#...',
    '..###..##hhhhhh##..###..',
    '..#S#.#hhccccccsh#.#S#..',
    '..#S#.#hccaaaaact#.#S#..',
    '..#S##tccttttttttc##S#..',
    '...#r#tcttttttttTt#R#...',
    '...#r#TTTTTTTTTTTT#R#...',
    '...#rrrrrrrrrrrrrrrR#...',
    '...#roooooooooooooOR#...',
    '....#roooooooooooOR#....',
    '....#roooooooooooOR#....',
    '.....#roooooooooOR#.....',
    '.....#rOOOOOOOOOOR#.....',
    '......#RRRRRRRRRR#......',
    '.......##########.......',
    '........................',
    '........................',
  ],
  sierra: [ // 3
    '........................',
    '........................',
    '....#######.............',
    '..##ddddddd##...........',
    '.#ddddddddddd#..........',
    '#dd###ddd###dd##########',
    '#d#DDD#d#DDD#dsssssssss#',
    '#d#D#D#d#D#D#dssgssssss#',
    '#d#DDD#d#DDD#dssssgssss#',
    '#dd###ddd###dggggggggg#.',
    '.#dddddddddd#gggggggg#..',
    '..##ddddddd#GGGGGGGG#...',
    '....#######G#G#G#G#G#...',
    '..........###########...',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  pelo: [ // 4
    '........................',
    '........########........',
    '......##nnnnnnnn##......',
    '.....#nnnnnnnnnnnn#.....',
    '....#nnnnnnnnnnnnnn#....',
    '...#nnnnnnnnnnnnnnnn#...',
    '...#nnnnnNnnnnNnnnnn#...',
    '..#nnnnnnnnnnnnnnnnnn#..',
    '..#nnn#pppppppppp#nnn#..',
    '..#nn#pppppppppppp#nn#..',
    '..#nn#pkkppppppkkp#nn#..',
    '..#nn#pkkppppppkkp#nn#..',
    '..#nn#pppppppppppp#nn#..',
    '..#nn#ppppppppppppp#n#..',
    '..#nn#ppppppkkppppp#n#..',
    '..#nn#pppppppppppp#nn#..',
    '..#nnn#pppppppppp#nnn#..',
    '..#nnn##########nnnnn#..',
    '..#nnnnn#....#nnnnnnn#..',
    '..#nnnnn#....#nnnnnn#...',
    '...#nnn#......#nnnnn#...',
    '...#nn#........#nnn#....',
    '....##..........###.....',
    '........................',
  ],
  puente: [ // 5
    '........................',
    '........................',
    '..####################..',
    '..#ssssssssssssssssss#..',
    '..#sggggggggggggggggs#..',
    '..#gGgGgGgGgGgGgGgGgG#..',
    '..#GGGGGGGGGGGGGGGGGG#..',
    '..#sssss########sssss#..',
    '..#gggg#cccccccc#gggg#..',
    '..#ggG#caaaaaaaac#Ggg#..',
    '..#gG#caaaaaaaaaac#Gg#..',
    '..#GG#caaaaaaaaaac#GG#..',
    '..#GG#caaaaaaaaaac#GG#..',
    '.#ll#caaaaaaaaaaaac#ll#.',
    '#lvv#caaaaaaaaaaaac#vvl#',
    '#vvv#caaaaaaaaaaaac#vvv#',
    '#vvV#caaaaaaaaaaaac#Vvv#',
    '#VVV#CCCCCCCCCCCCCC#VVV#',
    '..####################..',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  'numero-ocho': [ // 6
    '........................',
    '........########........',
    '......##cccccccc##......',
    '.....#ccttttttttcT#.....',
    '....#cctt######ttcT#....',
    '....#ctt#......#tcTT#...',
    '....#ctt#......#tcTT#...',
    '....#cctt######ttcTT#...',
    '.....#ccttttttttcTT#....',
    '....##ccctttttttcTT##...',
    '...#cccctttttttttccTT#..',
    '..#cccttt######tttcCTT#.',
    '..#cctt#........#tcCTTT#',
    '..#cctt#........#tcCTTT#',
    '..#cctt#........#tcCTTT#',
    '..#cccttt######tttcCTTT#',
    '...#cccctttttttttccTTT#.',
    '....##ccctttttttcTTT##..',
    '......##TTTTTTTTTT##....',
    '........##########......',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  'numero-cero': [ // 7
    '........................',
    '........########........',
    '......##MMMMMMMM##......',
    '.....#MMmmmmmmmmMY#.....',
    '....#MMmm######mmMY#....',
    '...#MMmm#......#mmMYY#..',
    '..#MMmm#........#mmMYY#.',
    '..#MMmm#........#mmMYY#.',
    '..#MMmm#........#mmMYY#.',
    '..#MMmm#........#mmMYY#.',
    '..#MMmm#........#mmMYY#.',
    '..#MMmm#........#mmMYY#.',
    '..#MMmm#........#mmMYY#.',
    '..#MMmm#........#mmMYY#.',
    '..#MMmm#........#mmMYY#.',
    '...#MMmm#......#mmMYY#..',
    '....#MMmm######mmMYY#...',
    '.....#MMmmmmmmmmMYY#....',
    '......##MMMMMMMMYY##....',
    '........##########......',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  'osito-grande': [ // 8
    '........................',
    '..####............####..',
    '.#dddd#..........#dddd#.',
    '.#dqqd#..........#dqqd#.',
    '.#dddd#..######..#dddd#.',
    '..####.##dddddd##.####..',
    '......#dddddddddd#......',
    '.....#dddddddddddd#.....',
    '.....#ddkddddddkdd#.....',
    '....#dddd######dddd#....',
    '....#ddd#qqqqqq#ddd#....',
    '....#ddd#qqkqqq#ddd#....',
    '.....#dd#qqqqqq#dd#.....',
    '......##dd####dd##......',
    '....##dddddddddddd##....',
    '...#dddddddddddddddd#...',
    '..#dddd#qqqqqqqq#dddd#..',
    '..#dddd#qqqqqqqq#dddd#..',
    '..#dddd#qqqqqqqq#dddd#..',
    '...#dddd#qqqqqq#dddd#...',
    '....#ddd########ddd#....',
    '....#dddd#....#dddd#....',
    '.....####......####.....',
    '........................',
  ],
  'osito-pequeno': [ // 9
    '........................',
    '........................',
    '........................',
    '.....##........##.......',
    '....#dd#......#dd#......',
    '....#qd#.####.#qd#......',
    '.....##.#dddd#.##.......',
    '.......#dddddd#.........',
    '.......#dkddkd#.........',
    '.......#d#qq#d#.........',
    '........#d##d#..........',
    '......##dddddd##........',
    '.....#dddddddddd#.......',
    '.....#dd#qqqq#dd#.......',
    '.....#dd#qqqq#dd#.......',
    '......##dddddd##........',
    '......#dd#..#dd#........',
    '.......##....##.........',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  'cuchara-limpia': [ // 10
    '........................',
    '..........#####.........',
    '.........#sssss#..#M#...',
    '........#swwwwws#MMM#...',
    '.......#swwwwwwws#M#....',
    '.......#swwwwwwws#......',
    '........#swwwwws#.......',
    '.........#sssss#........',
    '..........#ggg#.........',
    '...........#g#..........',
    '............#g#.........',
    '.............#g#........',
    '..............#g#.......',
    '...............#g#......',
    '................#g#.....',
    '.................#g#....',
    '..................#g#...',
    '...................#g#..',
    '....................#g#.',
    '....................#G#.',
    '.....................##.',
    '........................',
    '........................',
    '........................',
  ],
  'cuchara-sucia': [ // 11
    '........................',
    '..........#####.........',
    '.........#sssss#........',
    '........#snnnnns#.......',
    '.......#snnnnnnnns#.....',
    '.......#snNNNNNnns#.....',
    '........#snnnnnns#......',
    '.........#sNNNs#........',
    '..........#nnn#.........',
    '...........#n#..........',
    '............#n#.........',
    '.............#g#........',
    '..............#n#.......',
    '...............#g#......',
    '................#n#.....',
    '.................#g#....',
    '..................#n#...',
    '...................#g#..',
    '....................#g#.',
    '....................#G#.',
    '.....................##.',
    '........................',
    '........................',
    '........................',
  ],
  'caja-abierta': [ // 12
    '........................',
    '........#d#..#d#........',
    '.......#ddd##ddd#.......',
    '......#dddd##dddd#......',
    '.....#dddddddddddd#.....',
    '....#dddddddddddddd#....',
    '....#d#rrrr##vvvv#d#....',
    '...#dd#rrrr##vvvv#dd#...',
    '...#dd#mmmm##bbbb#dd#...',
    '..#dddddddddddddddddd#..',
    '..#dddddddddddddddddd#..',
    '..#dddddddddddddddddd#..',
    '..#dnnnnnnnnnnnnnnnnD#..',
    '..#dnnnnnnnnnnnnnnnnD#..',
    '..#dnnnnnnnnnnnnnnnnD#..',
    '..#dnnnnnnnnnnnnnnnnD#..',
    '..#dnnnnnnnnnnnnnnnnD#..',
    '..#dnnnnnnnnnnnnnnnnD#..',
    '..#dnnnnnnnnnnnnnnnnD#..',
    '..#DDDDDDDDDDDDDDDDDD#..',
    '..####################..',
    '........................',
    '........................',
    '........................',
  ],
  'caja-cerrada': [ // 13
    '........................',
    '.........######.........',
    '........#rrrrrr#........',
    '.......#rr####rr#.......',
    '......#rr#dddd#rr#......',
    '.....#dddd#rr#dddd#.....',
    '....#dddddd#r#dddddd#...',
    '...#ddddddd#r#ddddddd#..',
    '..#dddddddd#r#dddddddd#.',
    '..#dddddddd#r#dddddddd#.',
    '..####################..',
    '..#ddddddd#r#dddddddd#..',
    '..#dnnnnnn#r#nnnnnnnD#..',
    '..#dnnnnnn#r#nnnnnnnD#..',
    '..#dnnnnnn#r#nnnnnnnD#..',
    '..#drrrrrrrrrrrrrrrrD#..',
    '..#dnnnnnn#r#nnnnnnnD#..',
    '..#dnnnnnn#r#nnnnnnnD#..',
    '..#dnnnnnn#r#nnnnnnnD#..',
    '..#DDDDDDD#R#DDDDDDDD#..',
    '..####################..',
    '........................',
    '........................',
    '........................',
  ],
  'vaso-frio': [ // 14
    '........................',
    '..#c#............#c#....',
    '...#cc#........#cc#.....',
    '....#c#........#c#......',
    '....##############......',
    '....#cccccccccccc#......',
    '....#c#wwww##wwww#......',
    '....#c#wwww##wwww#......',
    '....#caaaaaaaaaaaC#.....',
    '....#caaaaaaaaaaaC#.....',
    '....#caaaaaaaaaaaC#.....',
    '....#caaaaaaaaaaaC#.....',
    '.....#caaaaaaaaaC#......',
    '.....#caaaaaaaaaC#......',
    '.....#caaaaaaaaaC#......',
    '......#caaaaaaaC#.......',
    '......#caaaaaaaC#.......',
    '......#caaaaaaaC#.......',
    '.......#caaaaaC#........',
    '.......#caaaaaC#........',
    '........#CCCCC#.........',
    '.........#####..........',
    '........................',
    '........................',
  ],
  'vaso-caliente': [ // 15
    '........................',
    '....#s#...#s#...#s#.....',
    '.....#s#...#s#...#s#....',
    '....#s#...#s#...#s#.....',
    '.....#s#...#s#...#s#....',
    '...##############.......',
    '...#hhhhhhhhhhhh#.......',
    '...#hndddddddddN#..###..',
    '...#hndddddddddN#.#rrr#.',
    '...#rrrrrrrrrrrr##r#..#.',
    '...#roooooooooooRr#...#.',
    '...#roooooooooooRr#...#.',
    '....#roooooooooORr#...#.',
    '....#roooooooooOR#r#..#.',
    '....#roooooooooOR##rrr#.',
    '.....#roooooooOR#..###..',
    '.....#roooooooOR#.......',
    '......#roooooOR#........',
    '......#rOOOOOOR#........',
    '.......#RRRRRR#.........',
    '........######..........',
    '........................',
    '........................',
    '........................',
  ],
  'bombilla-encendida': [ // 16
    '........................',
    '....#M#...#M#...#M#.....',
    '.....#M#..#M#..#M#......',
    '.......########.........',
    '.....##MMMMMMMM##.......',
    '...#M#MMwwwwwwMM#M#.....',
    '..#M#MMwwwwwwwwMM#M#....',
    '..#M#MMmmmmmmmmMM#M#....',
    '...#M#MMmmmmmmMM#M#.....',
    '....#MMmmmmmmmmMY#......',
    '.....#MMmmmmmmMY#.......',
    '......#MMmmmmMY#........',
    '.......#MMmmMY#.........',
    '........#YYYY#..........',
    '........#ssss#..........',
    '........#GGGG#..........',
    '........#ssss#..........',
    '........#GGGG#..........',
    '.........#ss#...........',
    '..........##............',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  'bombilla-apagada': [ // 17
    '........................',
    '........................',
    '........................',
    '.......########.........',
    '.....##ssssssss##.......',
    '....#sswwwwwwwwss#......',
    '...#sswwwwwwwwwwss#.....',
    '...#ssggggggggggss#.....',
    '...#ssggggggggggss#.....',
    '....#ssggggggggGG#......',
    '.....#ssggggggGG#.......',
    '......#ssggggGG#........',
    '.......#ssggGG#.........',
    '........#GGGG#..........',
    '........#ssss#..........',
    '........#GGGG#..........',
    '........#ssss#..........',
    '........#GGGG#..........',
    '.........#ss#...........',
    '..........##............',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  'cesta-llena': [ // 18
    '........................',
    '.........######.........',
    '.......##dddddd##.......',
    '......#dddddddddd#......',
    '.....#dddd####dddd#.....',
    '....#dddd#....#dddd#....',
    '...#dddd#..##..#dddd#...',
    '...#ddd##rrrrrr##ddd#...',
    '..#ddd#rrwwwwwwrr#ddd#..',
    '..#dd#rrwwwwwwwwrr#dd#..',
    '..#dd#rllvvvvvvlrr#dd#..',
    '.#dddd#lvvvvvvvvl#dddd#.',
    '#dddddd#lvvvvvvl#dddddd#',
    '#dnnnnnnnnnnnnnnnnnnnnD#',
    '#dnnnnnnnnnnnnnnnnnnnnD#',
    '.#dndndndndndndndndndD#.',
    '.#dnnnnnnnnnnnnnnnnnnD#.',
    '..#dndndndndndndndndD#..',
    '..#dnnnnnnnnnnnnnnnnD#..',
    '...#dndndndndndndndD#...',
    '...#dnnnnnnnnnnnnnnD#...',
    '....#DDDDDDDDDDDDDD#....',
    '.....##############.....',
    '........................',
  ],
  'cesta-vacia': [ // 19
    '........................',
    '.........######.........',
    '.......##dddddd##.......',
    '......#dddddddddd#......',
    '.....#dddd####dddd#.....',
    '....#dddd#....#dddd#....',
    '...#dddd#......#dddd#...',
    '...#dddd#......#dddd#...',
    '..#dddd#........#dddd#..',
    '..#dddd#........#dddd#..',
    '..#dddd#........#dddd#..',
    '.#dddddd########dddddd#.',
    '#dddddddddddddddddddddd#',
    '#dnnnnnnnnnnnnnnnnnnnnD#',
    '#dnnnnnnnnnnnnnnnnnnnnD#',
    '.#dndndndndndndndndndD#.',
    '.#dnnnnnnnnnnnnnnnnnnD#.',
    '..#dndndndndndndndndD#..',
    '..#dnnnnnnnnnnnnnnnnD#..',
    '...#dndndndndndndndD#...',
    '...#dnnnnnnnnnnnnnnD#...',
    '....#DDDDDDDDDDDDDD#....',
    '.....##############.....',
    '........................',
  ],
  'coche-subiendo': [ // 20
    '........................',
    '...............#####....',
    '..............#rrrrr#...',
    '............##rwwwwwr#..',
    '...........#rrrwwwwwrr#.',
    '..........#rrrrrrrrrrr#.',
    '.........#rrrrrrrrrrrr#.',
    '........#rrrrrrrrrrrr#..',
    '.......#kk#rrrrrrr#kk#..',
    '......#kSSk#rrrrr#kSSk#.',
    '.......#kk#.......#kk#..',
    '........................',
    '.................####...',
    '.............####llll#..',
    '.........####vvvvvvvv#..',
    '.....####vvvvvvvvvvvv#..',
    '.####vvvvvvvvvvvvvvvv#..',
    '#vvvvvvvvvvvvvvvvvvvv#..',
    '#VVVVVVVVVVVVVVVVVVVV#..',
    '..###################...',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  'coche-bajando': [ // 21
    '........................',
    '....#####...............',
    '...#rrrrr#..............',
    '..#rwwwwwr##............',
    '.#rrwwwwwrrr#...........',
    '.#rrrrrrrrrrr#..........',
    '.#rrrrrrrrrrrr#.........',
    '..#rrrrrrrrrrrr#........',
    '..#kk#rrrrrrr#kk#.......',
    '.#kSSk#rrrrr#kSSk#......',
    '..#kk#.......#kk#.......',
    '........................',
    '...####.................',
    '..#llll####.............',
    '..#vvvvvvvv####.........',
    '..#vvvvvvvvvvvv####.....',
    '..#vvvvvvvvvvvvvvvv####.',
    '..#vvvvvvvvvvvvvvvvvvvv#',
    '..#VVVVVVVVVVVVVVVVVVVV#',
    '...###################..',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  'juguete-dentro': [ // 22
    '........................',
    '.........######.........',
    '........#mmmmmm#........',
    '.......#mmkmmkmm#.......',
    '.......#mmmmmmmm#.......',
    '........#mmoomm#........',
    '.......#d#mmmm#d#.......',
    '......#dd#mmmm#dd#......',
    '.....#dddddddddddd#.....',
    '....#dddddddddddddd#....',
    '....#d#dddddddddd#d#....',
    '...#dd#dddddddddd#dd#...',
    '..#dddddddddddddddddd#..',
    '..#dnnnnnnnnnnnnnnnnD#..',
    '..#dnnnnnnnnnnnnnnnnD#..',
    '..#dnnnnnnnnnnnnnnnnD#..',
    '..#dnnnnnnnnnnnnnnnnD#..',
    '..#dnnnnnnnnnnnnnnnnD#..',
    '..#dnnnnnnnnnnnnnnnnD#..',
    '..#DDDDDDDDDDDDDDDDDD#..',
    '..####################..',
    '........................',
    '........................',
    '........................',
  ],
  'juguete-fuera': [ // 23
    '........................',
    '........................',
    '....######..............',
    '...#mmmmmm#.............',
    '..#mmkmmkmm#............',
    '..#mmmmmmmm#............',
    '...#mmoomm#...########..',
    '..#d#mmmm#d#.#dddddddd#.',
    '.#dd#mmmm#dd#dddddddddd#',
    '.#dddddddddd#dnnnnnnnnD#',
    '..#dnnnnnnD##dnnnnnnnnD#',
    '..#dnnnnnnD##dnnnnnnnnD#',
    '..#dnnnnnnD##dnnnnnnnnD#',
    '..#dnnnnnnD##dnnnnnnnnD#',
    '..#dnnnnnnD##dnnnnnnnnD#',
    '..#dnnnnnnD##dnnnnnnnnD#',
    '..#DDDDDDDD##DDDDDDDDDD#',
    '...########..##########.',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  comer: [ // 24
    '........................',
    '..........#####.........',
    '.........#lllll#........',
    '........#lvvvvvV#.......',
    '.........#VV#VV#........',
    '..........#n#...........',
    '.......####n####........',
    '.....##rrrrrrrrr##......',
    '....#rrwwwwwwwwwrr#.....',
    '...#rrwwwwwwwwwwwrr#....',
    '..#rrwwrrrrrrrrrwwrr#...',
    '..#rrwrrrr..rrrrrwrr#...',
    '..#rrwrrr....rrrrwrr#...',
    '..#rrwrrrr..rrrrrwrr#...',
    '..#rrwrrrrrrrrrrrwrr#...',
    '...#rrwrrrrrrrrrwrr#....',
    '....#rrwrrrrrrrwrr#.....',
    '.....#rrwwwwwwwrr#......',
    '......##rrrrrrr##.......',
    '........#######.........',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  dormir: [ // 25
    '........................',
    '...................#M#..',
    '..................#MMM#.',
    '.................#M#M#..',
    '........########..#M#...',
    '......##cccccccc##......',
    '.....#ccbbbbbbbbcc#.....',
    '....#cbbbbbbbbbbbbc#....',
    '...#cbbbbbbbbbbbbbbc#...',
    '..#cbbbbbbbbbbbbbbbbc#..',
    '..#cbbbbbbbbbbbbbbbbc#..',
    '..#cbbbbbbbbbbbbbbbbc#..',
    '...#cbbbbbbbbbbbbbbc#...',
    '....#cbbbbbbbbbbbbc#....',
    '.....#ccbbbbbbbbcc#.....',
    '......##cccccccc##......',
    '........########........',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  soplar: [ // 26
    '........................',
    '.......#########........',
    '.....##ppppppppp##......',
    '....#ppppppppppppp#.....',
    '...#pppppppppppppp##....',
    '...#pppp#kk#pppppppp#...',
    '..#ppppp#kk#ppppppppp#..',
    '..#pppppppppppppppp##...',
    '..#ppppppppppppppp#.....',
    '..#pppppppppppppp#..cc..',
    '..#ppppppppppppp#..cccc.',
    '..#pppppppp#####..cccccc',
    '..#ppppppp#OOO#..ccccccc',
    '..#pppppppp#####..cccccc',
    '..#ppppppppppppp#..cccc.',
    '..#pppppppppppppp#..cc..',
    '..#OOOOOOOOOOOOOO#......',
    '..#OOOOOOOOOOOOO#.......',
    '...#OOOOOOOOOOO#........',
    '....##OOOOOOO##.........',
    '......#######...........',
    '........................',
    '........................',
    '........................',
  ],
  banar: [ // 27
    '........................',
    '..c....................c',
    '...c...c...........c....',
    '.....c.....c...c........',
    '..c.....c.......c.....c.',
    '....c........c.......c..',
    '........................',
    '.######################.',
    '.#gggggggggggggggggggg#.',
    '.#hhhhhhhhhhhhhhhhhhhh#.',
    '.#tttttttttttttttttttt#.',
    '.#tccttttcctttttcctttt#.',
    '.#tttttttttttttttttttt#.',
    '.#tttttttttttttttttttt#.',
    '.#Tttttttttttttttttttt#.',
    '.#TTTTTTTTTTTTTTTTTTTT#.',
    '..#TTTTTTTTTTTTTTTTTT#..',
    '..####################..',
    '....#GG#........#GG#....',
    '....#GG#........#GG#....',
    '...##GG##......##GG##...',
    '...#GGGG#......#GGGG#...',
    '...######......######...',
    '........................',
  ],
  vestir: [ // 28
    '........................',
    '.......###...###........',
    '.....##aaa###aaa##......',
    '...##aaaaaaaaaaaaa##....',
    '..#aaaaaaaaaaaaaaaaa#...',
    '.#aacaaaaaaaaaaaaacaa#..',
    '.#acCCaaaaaaaaaaacCCa#..',
    '.#aCC#aaaaaaaaaa#CCaa#..',
    '..###aaaaaaaaaaaa###....',
    '....#aacaaaaaaaca#......',
    '....#acaacaaaacaa#......',
    '....#aaaaaaaaaaaa#......',
    '....#aacaaaaaaaca#......',
    '....#acaacaaaacaa#......',
    '....#aaaaaaaaaaaa#......',
    '....#aacaaaaaaaca#......',
    '....#acaacaaaacaa#......',
    '....#aaaaaaaaaaaa#......',
    '....#CCCCCCCCCCCC#......',
    '.....############.......',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  correr: [ // 29
    '........................',
    '........................',
    '..........#####.........',
    '.........#rrrrr#........',
    '........#rrrrrrr#.......',
    '.......#rrrrrrrrr#......',
    '......#rrwwrrrwwrr#.....',
    '.....#rrwwrrrwwrrr#.....',
    '....#rrrrrrrrrrrrrr#....',
    '...#rrrrrrrrrrrrrrrr#...',
    '..#rrrrrrrrrrrrrrrrrr#..',
    '.#rrrrrrrrrrrrrrrrrrrr#.',
    '#rrrrrrrrrrrrrrrrrrrrrr#',
    '#ssssssssssssssssssssss#',
    '#ssssssssssssssssssssss#',
    '#GGGGGGGGGGGGGGGGGGGGGG#',
    '.######################.',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  nadar: [ // 30
    '........................',
    '........########........',
    '......##rrrrrrrr##......',
    '.....#rrwwwwwwwwrr#.....',
    '....#rrww######wwrr#....',
    '...#rrww#......#wwrr#...',
    '..#rrww#........#wwrr#..',
    '..#rrww#..####..#wwrr#..',
    '..#wwww#.#cccc#.#wwww#..',
    '..#wwww#.#caac#.#wwww#..',
    '..#wwww#.#caac#.#wwww#..',
    '..#wwww#.#cccc#.#wwww#..',
    '..#rrww#..####..#wwrr#..',
    '..#rrww#........#wwrr#..',
    '...#rrww#......#wwrr#...',
    '....#rrww######wwrr#....',
    '.....#rrwwwwwwwwrr#.....',
    '......##rrrrrrrr##......',
    '........########........',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  parar: [ // 31
    '........................',
    '.......##########.......',
    '.....##rrrrrrrrrr##.....',
    '....#rrrrrrrrrrrrrr#....',
    '...#rrrrrrrrrrrrrrrr#...',
    '..#rrrr#wwwwwwww#rrrr#..',
    '..#rrr#wwwwwwwwww#rrr#..',
    '.#rrr#ww#rr#rr#ww#rrr#..',
    '.#rrr#ww#rr#rr#ww#rrr#..',
    '.#rrr#ww#rr#rr#ww#rrr#..',
    '.#rrr#ww#rr#rr#ww#rrr#..',
    '.#rrr#ww#rr#rr#ww#rrr#..',
    '.#rrr#ww#rr#rr#ww#rrr#..',
    '.#rrr#ww#wwwwww#w#rrr#..',
    '..#rrr#wwwwwwwwww#rrr#..',
    '..#rrrr#wwwwwwww#rrrr#..',
    '...#rrrrrrrrrrrrrrrr#...',
    '....#rrrrrrrrrrrrrr#....',
    '.....##rrrrrrrrrr##.....',
    '.......##########.......',
    '...........##...........',
    '...........##...........',
    '........................',
    '........................',
  ],
  pajaro: [ // 32
    '........................',
    '.........######.........',
    '.......##aaaaaa##.......',
    '......#aaacccaacc#......',
    '.....#aaaakcaaaaac#.....',
    '....#aaaaacccaaaac#oo#..',
    '....#aaaaaccaaaaa#oooo#.',
    '....#aaaaaccaaaaaa#oo#..',
    '....#aaaaccaaaaaaa#.....',
    '.....#aaccaaaaaaa#......',
    '.....#accaaaaaaa#.......',
    '......#caaaaaaa#........',
    '.......#aaaaaa#.........',
    '........#aaaa#..........',
    '.......##aaaa##.........',
    '......#aaaaaaC#.........',
    '.....#aaCCCCCC#.........',
    '....#aCCCCCC#...........',
    '.....#d#..#d#...........',
    '....#dd#..#dd#..........',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  jabon: [ // 33
    '........................',
    '............#w#.........',
    '...........#www#........',
    '..........#wwwww#.......',
    '...........#www#........',
    '......#w#...#w#.........',
    '.....#www#..............',
    '......#w#...............',
    '....##############......',
    '..##cccccccccccccc##....',
    '.#cctttttttttttttttc#...',
    '#cctttttttttttttttttc#..',
    '#cttttttttttttttttttt#..',
    '#cttttttttttttttttttt#..',
    '#cttttttttttttttttttt#..',
    '#cttttttttttttttttttt#..',
    '#cttttttttttttttttttt#..',
    '.#cTTTTTTTTTTTTTTTTT#...',
    '..##TTTTTTTTTTTTTT##....',
    '....##############......',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  'vaso-leche': [ // 34
    '........................',
    '............#r#.........',
    '...........#r#..........',
    '..........#r#...........',
    '.........#r#............',
    '....##############......',
    '....#cccccccccccc#......',
    '....#c#hhhhhhhh#c#......',
    '....#c#hhhhhhhh#c#......',
    '....#chhhhhhhrh#cC#.....',
    '....#chhhhhhrhh#cC#.....',
    '....#chhhhhrhhh#cC#.....',
    '.....#chhhhrhh#cC#......',
    '.....#chhhhrhh#cC#......',
    '.....#chhhhrhh#cC#......',
    '......#chhhhhh#C#.......',
    '......#chhhhhh#C#.......',
    '......#chhhhhh#C#.......',
    '.......#chhhh#C#........',
    '.......#chhhh#C#........',
    '........#CCCC#..........',
    '.........####...........',
    '........................',
    '........................',
  ],
  cesta: [ // 35
    '........................',
    '.........######.........',
    '.......##dddddd##.......',
    '......#dddddddddd#......',
    '.....#dddd####dddd#.....',
    '....#dddd#....#dddd#....',
    '...#dddd#......#dddd#...',
    '...#dddd#......#dddd#...',
    '..#dddd#........#dddd#..',
    '..#dddd#........#dddd#..',
    '..#dddd#........#dddd#..',
    '.#dddddd########dddddd#.',
    '#dddddddddddddddddddddd#',
    '#dnnnnnnnnnnnnnnnnnnnnD#',
    '#dnnnnnnnnnnnnnnnnnnnnD#',
    '.#dndndndndndndndndndD#.',
    '.#dnnnnnnnnnnnnnnnnnnD#.',
    '..#dndndndndndndndndD#..',
    '..#dnnnnnnnnnnnnnnnnD#..',
    '...#dndndndndndndndD#...',
    '...#dnnnnnnnnnnnnnnD#...',
    '....#DDDDDDDDDDDDDD#....',
    '.....##############.....',
    '........................',
  ],
  cuchara: [ // 36
    '........................',
    '..........#####.........',
    '.........#sssss#..#M#...',
    '........#swwwwws#MMM#...',
    '.......#swwwwwwws#M#....',
    '.......#swwwwwwws#......',
    '........#swwwwws#.......',
    '.........#sssss#........',
    '..........#ggg#.........',
    '...........#g#..........',
    '............#g#.........',
    '.............#g#........',
    '..............#g#.......',
    '...............#g#......',
    '................#g#.....',
    '.................#g#....',
    '..................#g#...',
    '...................#g#..',
    '....................#g#.',
    '....................#G#.',
    '.....................##.',
    '........................',
    '........................',
    '........................',
  ],
  vaso: [ // 37
    '........................',
    '........................',
    '........................',
    '........................',
    '....##############......',
    '....#cccccccccccc#......',
    '....#c#wwwwwwww#c#......',
    '....#c#wwwwwwww#c#......',
    '....#caaaaaaaaaaaC#.....',
    '....#caaaaaaaaaaaC#.....',
    '....#caaaaaaaaaaaC#.....',
    '....#caaaaaaaaaaaC#.....',
    '.....#caaaaaaaaaC#......',
    '.....#caaaaaaaaaC#......',
    '.....#caaaaaaaaaC#......',
    '......#caaaaaaaC#.......',
    '......#caaaaaaaC#.......',
    '......#caaaaaaaC#.......',
    '.......#caaaaaC#........',
    '.......#caaaaaC#........',
    '........#CCCCC#.........',
    '.........#####..........',
    '........................',
    '........................',
  ],
  abrazo: [ // 38
    '........................',
    '....####........####....',
    '..##rrrr##....##rrrr##..',
    '.#rrwwwwrr#..#rrwwwwrr#.',
    '#rrwwwwwwrr##rrwwwwwwrr#',
    '#rrwwwwwwwwwwrrwwwwwwrr#',
    '#rrrrrrrrrrrrrrrrrrrrrr#',
    '#rrrrrrrrrrrrrrrrrrrrrr#',
    '.#rrrrrrrrrrrrrrrrrrrr#.',
    '..#rrrrrrrrrrrrrrrrrr#..',
    '...#rrrrrrrrrrrrrrrr#...',
    '....#rrrrrrrrrrrrrr#....',
    '.....#rrrrrrrrrrrr#.....',
    '......#rrrrrrrrrr#......',
    '.......#rrrrrrrr#.......',
    '........#rrrrrr#........',
    '.........#rrrr#.........',
    '..........#rr#..........',
    '...........##...........',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  rueda: [ // 39
    '........................',
    '........########........',
    '......##kkkkkkkk##......',
    '.....#kkSSSSSSSSkk#.....',
    '....#kkSS######SSkk#....',
    '...#kkSS#ssssss#SSkk#...',
    '..#kkSS#ssggggss#SSkk#..',
    '..#kkSS#sggGGggs#SSkk#..',
    '.#kkSS#sgG#ss#Ggs#SSkk#.',
    '.#kkSS#sgGs##sGgs#SSkk#.',
    '.#kkSS#sgGs##sGgs#SSkk#.',
    '.#kkSS#sgG#ss#Ggs#SSkk#.',
    '..#kkSS#sggGGggs#SSkk#..',
    '..#kkSS#ssggggss#SSkk#..',
    '...#kkSS#ssssss#SSkk#...',
    '....#kkSS######SSkk#....',
    '.....#kkSSSSSSSSkk#.....',
    '......##kkkkkkkk##......',
    '........########........',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  'manos-mojadas': [ // 40
    '........................',
    '.......#c#....#c#.......',
    '......#ca#...#ca#.......',
    '.......#c#....#c#.......',
    '.....#p#........#p#.....',
    '....#pp#.#p#..#p#pp#....',
    '...#pp#.#pp#..#pp#pp#...',
    '...#pp#.#pp#..#pp#pp#...',
    '..#ppp#.#pp#..#pp#ppp#..',
    '..#pppp##pp#..#pp##ppp#.',
    '..#pppppppp#..#ppppppp#.',
    '..#pppppppp#..#ppppppp#.',
    '...#pppppp#....#ppppp#..',
    '...#qqqqqq#....#qqqqq#..',
    '....#qqqq#......#qqq#...',
    '.....####........###....',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  pluma: [ // 41
    '........................',
    '.................###....',
    '...............##ccc#...',
    '..............#ccttt#...',
    '.............#cctttt#...',
    '............#ccttttt#...',
    '...........#cctttt#t#...',
    '..........#cctttt#tt#...',
    '.........#cctttt#ttt#...',
    '........#cctttt#tttt#...',
    '.......#cctttt#ttttt#...',
    '......#cctttt#tttttt#...',
    '.....#cctttt#tttttt#....',
    '....#cctttt#tttttt#.....',
    '...#cctttt#tttttt#......',
    '..#cctttt#tttttt#.......',
    '.#cctttt#tttttt#........',
    '..####t#tttttt#.........',
    '......#tttttt#..........',
    '.......#n###............',
    '........#n#.............',
    '.........#n#............',
    '..........##............',
    '........................',
  ],
  tubo: [ // 42
    '........................',
    '........................',
    '.......##########.......',
    '.....##cccccccccc##.....',
    '....#ccttttttttttcT#....',
    '...#cctt########ttcT#...',
    '..#cctt#kkkkkkkk#ttcT#..',
    '..#cctt#kkkkkkkk#ttcT#..',
    '..#cctt#kkkkkkkk#ttcT#..',
    '..#cctt#kkkkkkkk#ttcT#..',
    '..#cctt#kkkkkkkk#ttcT#..',
    '..#cctt#kkkkkkkk#ttcT#..',
    '..#cctt#kkkkkkkk#ttcT#..',
    '..#cctt#kkkkkkkk#ttcT#..',
    '..#cctt#kkkkkkkk#ttcT#..',
    '..#cctt#kkkkkkkk#ttcT#..',
    '...#cctt########ttcTT#..',
    '....#ccttttttttttcTT#...',
    '.....##TTTTTTTTTT##.....',
    '.......##########.......',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  saltar: [ // 43
    '.........######.........',
    '........#pppppp#........',
    '........#pkppkp#........',
    '........#pppppp#........',
    '.........#pppp#.........',
    '###........##........###',
    '#pp##....######....##pp#',
    '#pppp##.#rrrrrr#.##pppp#',
    '.##pppp#rrrrrrrr#pppp##.',
    '...##pppprrrrrrpppp##...',
    '.....##prrrrrrrrrp##....',
    '.......#rrrrrrrr#.......',
    '.......#rrrrrrrr#.......',
    '.......#RRRRRRRR#.......',
    '.......#aaaaaaaa#.......',
    '.......#aaaaaaaa#.......',
    '......##aa#..#aa##......',
    '.....#ppp#....#ppp#.....',
    '....#pppp#....#pppp#....',
    '...#ppppp#....#ppppp#...',
    '...#ppp#........#ppp#...',
    '...#####........#####...',
    '........................',
    '........................',
  ],
  esponja: [ // 44
    '........................',
    '........................',
    '........................',
    '....##############......',
    '..##MMMMMMMMMMMMMM##....',
    '.#MMmmmmmmmmmmmmmmMM#...',
    '#MMmmmmmmmmmmmmmmmmMM#..',
    '#Mmmm#YY#mmmm#YY#mmmMY#.',
    '#Mmm#YYYY#mm#YYYY#mmMYY#',
    '#Mmmm#YY#mmmm#YY#mmmMYY#',
    '#MmmmmmmmmmmmmmmmmmmMYY#',
    '#Mmm#YY#mmmm#YY#mmmmMYY#',
    '#Mmm#YY#mmmm#YY#mmmmMYY#',
    '#MmmmmmmmmmmmmmmmmmmMYY#',
    '#Mmmm#YY#mmmm#YY#mmmMYY#',
    '#Mmm#YYYY#mm#YYYY#mmMYY#',
    '#Mmmm#YY#mmmm#YY#mmmMYY#',
    '.#MMmmmmmmmmmmmmmmMYY#..',
    '..##YYYYYYYYYYYYYYYY##..',
    '....################....',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  lana: [ // 45
    '........................',
    '.........######.........',
    '......###bbbbbb###......',
    '....##bbbbbbbbbbbb##....',
    '...#bbbb##bbbb##bbbb#...',
    '..#bbbb#ww#bb#ww#bbbb#..',
    '.#bbbbbb##bbbb##bbbbbb#.',
    '.#bb##bbbbbbbbbbbb##bb#.',
    '#bb#ww#bbbb##bbbb#ww#bb#',
    '#bbb##bbbb#ww#bbbb##bbb#',
    '#bbbbbbbbbb##bbbbbbbbbb#',
    '#bbbbbb##bbbbbb##bbbbbb#',
    '#bbb###ww#bbbb#ww#bbbbb#',
    '.#bb#ww##bbbbbb##bbbbb#.',
    '.#bbb##bbbbbbbbbbbbbbb#.',
    '..#bbbbbbbbbbbbbbbbbb#..',
    '...#bbbbbbbbbbbbbbbb#...',
    '....##bbbbbbbbbbbb##....',
    '......###bbbbbb###......',
    '.........######...#dd#..',
    '...................#dd#.',
    '....................##..',
    '........................',
    '........................',
  ],
  lata: [ // 46
    '........................',
    '........########........',
    '......##ssssssss##......',
    '.....#ssggggggggss#.....',
    '....#ssggggggggggss#....',
    '....################....',
    '....#ssssssssssssss#....',
    '....#srrrrrrrrrrrrG#....',
    '....#srwwwwwwwwwwrG#....',
    '....#srwwwwwwwwwwrG#....',
    '....#srwwwwwwwwwwrG#....',
    '....#srrrrrrrrrrrrG#....',
    '....#srrrrrrrrrrrrG#....',
    '....#srrrrrrrrrrrrG#....',
    '....#ssssssssssssss#....',
    '....#sggggggggggggG#....',
    '....#sggggggggggggG#....',
    '....#sggggggggggggG#....',
    '.....#sggggggggggG#.....',
    '......##GGGGGGGG##......',
    '........########........',
    '........................',
    '........................',
    '........................',
  ],
  cuerda: [ // 47
    '........................',
    '........########........',
    '......##dddddddd##......',
    '.....#ddnnnnnnnndd#.....',
    '....#ddnn######nndd#....',
    '...#ddnn#......#nndd#...',
    '..#ddnn#........#nndd#..',
    '..#ddnn#..####..#nndd#..',
    '..#ddnn#.#dddd#.#nndd#..',
    '..#ddnn#.#dnnd#.#nndd#..',
    '..#ddnn#.#dnnd#.#nndd#..',
    '..#ddnn#.#dddd#.#nndd#..',
    '..#ddnn#..####..#nndd#..',
    '..#ddnn#........#nndd#..',
    '...#ddnn#......#nndd#...',
    '....#ddnn######nndd#....',
    '.....#ddnnnnnnnndd#.....',
    '......##dddddddd##......',
    '........########..#n#...',
    '...................#nn#.',
    '....................#n#.',
    '.....................##.',
    '........................',
    '........................',
  ],
  papel: [ // 48
    '........................',
    '..###################...',
    '..#hhhhhhhhhhhhhh##s#...',
    '..#hhhhhhhhhhhhhh#ss#...',
    '..#hhhhhhhhhhhhhh#####..',
    '..#hSSSSSSSSSSSShhhhh#..',
    '..#hhhhhhhhhhhhhhhhhh#..',
    '..#hSSSSSSSSSSSSSSShh#..',
    '..#hhhhhhhhhhhhhhhhhh#..',
    '..#hSSSSSSSSSSSSSSShh#..',
    '..#hhhhhhhhhhhhhhhhhh#..',
    '..#hSSSSSSSSSSSSSSShh#..',
    '..#hhhhhhhhhhhhhhhhhh#..',
    '..#hSSSSSSSSSSSSSSShh#..',
    '..#hhhhhhhhhhhhhhhhhh#..',
    '..#hSSSSSSSSSSSSSSShh#..',
    '..#hhhhhhhhhhhhhhhhhh#..',
    '..#hSSSSSSSSSSShhhhhh#..',
    '..#hhhhhhhhhhhhhhhhhh#..',
    '..#ssssssssssssssssss#..',
    '..###################...',
    '........................',
    '........................',
    '........................',
  ],
  mano: [ // 49
    '........................',
    '.......#p#.#p#.#p#......',
    '......#pp##pp##pp#.#p#..',
    '......#pp##pp##pp##pp#..',
    '.....#ppp##pp##pp##pp#..',
    '.....#pppp#pp##pp##pp#..',
    '....#pppppppppppppppp#..',
    '....#pppppppppppppppp#..',
    '....#pppppppppppppppp#..',
    '....#pppppppppppppppp#..',
    '....#pppppppppppppppp#..',
    '.....#pppppppppppppp#...',
    '......#pppppppppppp#....',
    '......#qqqqqqqqqqqq#....',
    '.......#qqqqqqqqqq#.....',
    '........#qqqqqqqq#......',
    '........#qqqqqqqq#......',
    '.........#qqqqqq#.......',
    '..........######........',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  'mano-limpia': [ // 50
    '........................',
    '.......#p#.#p#.#p#..#M#.',
    '......#pp##pp##pp#.#MMM#',
    '......#pp##pp##pp##p#M#.',
    '.....#ppp##pp##pp##pp#..',
    '.....#pppp#pp##pp##pp#..',
    '....#pppppppppppppppp#..',
    '..#M#pppppppppppppppp#..',
    '.#MMMpppppppppppppppp#..',
    '..#M#pppppppppppppppp#..',
    '....#pppppppppppppppp#..',
    '.....#pppppppppppppp#...',
    '......#pppppppppppp#....',
    '......#qqqqqqqqqqqq#.#M#',
    '.......#qqqqqqqqqq#.MMM#',
    '........#qqqqqqqq#...#M#',
    '........#qqqqqqqq#......',
    '.........#qqqqqq#.......',
    '..........######........',
    '...##....##....##.......',
    '..#cc#..#cc#..#cc#......',
    '..#cc#..#cc#..#cc#......',
    '...##....##....##.......',
    '........................',
  ],
  palo: [ // 51
    '........................',
    '...................##...',
    '..................#dd#..',
    '.................#dddd#.',
    '................#ddnndd#',
    '...............#ddnndd#.',
    '..............#ddnndd#..',
    '.............#ddnndd#...',
    '............#ddnndd#....',
    '.....#ll#..#ddnndd#.....',
    '....#lvvl##ddnndd#......',
    '.....#Vl#ddnndd#........',
    '.......#ddnndd#.........',
    '......#ddnndd#..........',
    '.....#ddnndd#...........',
    '....#ddnndd#............',
    '...#ddnndd#.............',
    '..#ddnndd#..............',
    '.#ddnndd#...............',
    '#ddnndd#................',
    '#DDDDDD#................',
    '########................',
    '........................',
    '........................',
  ],
  senalar: [ // 52
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '..#######...............',
    '.#ppppppp##############.',
    '.#pppppppppppppppppppp#.',
    '.#pppppppppppppppppppp#.',
    '.#ppppppp##############.',
    '.#ppppppppp#............',
    '.#pOOpOOppp#............',
    '.#ppppppppp#............',
    '.#pOOpOOppp#............',
    '.#ppppppppp#............',
    '.#pOOpOOppp#............',
    '.#ppppppppp#............',
    '.#OOOOOOOOO#............',
    '.#OOOOOOOOO#............',
    '..#########.............',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  'frio-cara': [ // 53
    '........................',
    '......#############.....',
    '....##bbbbbbbbbbbbb##...',
    '...#bbbbbbbbbbbbbbbbb#..',
    '...#BBBBBBBBBBBBBBBBB#..',
    '..##################....',
    '.#ttttttttttttttttttt#..',
    '#ttttttttttttttttttttt#.',
    '#tttttttttttttttttttttt#',
    '#tt#ccc#tttttt#ccc#tttt#',
    '#tt#ckc#tttttt#ckc#tttt#',
    '#tt#ccc#tttttt#ccc#tttt#',
    '#tttttttttttttttttttttt#',
    '#tttttttttttttttttttttt#',
    '#ttt##############ttttt#',
    '#ttt#wwwwwwwwwwww#tttt#.',
    '#ttt#w#w#w#w#w#ww#tttt#.',
    '#ttt#wwwwwwwwwwww#tttt#.',
    '#ttt#w#w#w#w#w#ww#ttt#..',
    '.#tt##############ttt#..',
    '.#TTTTTTTTTTTTTTTTTT#...',
    '..#TTTTTTTTTTTTTTTT#....',
    '...##############.......',
    '........................',
  ],
  torta: [ // 54
    '........................',
    '...........#M#..........',
    '..........#mmm#.........',
    '...........#r#..........',
    '...........#r#..........',
    '.......############.....',
    '.....##wwwwwwwwwwww##...',
    '....#wwwwwwwwwwwwwwww#..',
    '...#wwwwwwwwwwwwwwwwww#.',
    '..#wwwwwwwwwwwwwwwwwwww#',
    '..#wrrrrrrrrrrrrrrrrrrw#',
    '..#wrrrrrrrrrrrrrrrrrrw#',
    '..#wqqqqqqqqqqqqqqqqqqw#',
    '..#wqqqqqqqqqqqqqqqqqqw#',
    '..#wrrrrrrrrrrrrrrrrrrw#',
    '..#wqqqqqqqqqqqqqqqqqqw#',
    '..#wqqqqqqqqqqqqqqqqqqw#',
    '..#wddddddddddddddddddw#',
    '..#DDDDDDDDDDDDDDDDDDDD#',
    '...####################.',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  'color-rojo': [ // 55
    '........................',
    '.........######.........',
    '.......##wwwwww##.......',
    '......#wwrrrrrrww#......',
    '.....#wwrrrrrrrrww#.....',
    '....#wwrrrrrrrrrrww#....',
    '...#wwrrrrrrrrrrrrww#...',
    '..#wwrrrrrrrrrrrrrrww#..',
    '..#wwrrrrrrrrrrrrrrww#..',
    '..#wwrrrrrrrrrrrrrrww#..',
    '..#wwrrrrrrrrrrrrrrww#..',
    '..#wwrrrrrrrrrrrrrrww#..',
    '..#wwrrrrrrrrrrrrrrww#..',
    '..#wwrrrrrrrrrrrrrrww#..',
    '...#wwrrrrrrrrrrrrww#...',
    '....#wwrrrrrrrrrrww#....',
    '.....#wwrrrrrrrrww#.....',
    '......#wwrrrrrrww#......',
    '.......##RRRRRR##.......',
    '.........######.........',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  'color-azul': [ // 56
    '........................',
    '.........######.........',
    '.......##wwwwww##.......',
    '......#wwaaaaaaww#......',
    '.....#wwaaaaaaaaww#.....',
    '....#wwaaaaaaaaaaww#....',
    '...#wwaaaaaaaaaaaaww#...',
    '..#wwaaaaaaaaaaaaaaww#..',
    '..#wwaaaaaaaaaaaaaaww#..',
    '..#wwaaaaaaaaaaaaaaww#..',
    '..#wwaaaaaaaaaaaaaaww#..',
    '..#wwaaaaaaaaaaaaaaww#..',
    '..#wwaaaaaaaaaaaaaaww#..',
    '..#wwaaaaaaaaaaaaaaww#..',
    '...#wwaaaaaaaaaaaaww#...',
    '....#wwaaaaaaaaaaww#....',
    '.....#wwaaaaaaaaww#.....',
    '......#wwaaaaaaww#......',
    '.......##CCCCCC##.......',
    '.........######.........',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  'color-amarillo': [ // 57
    '........................',
    '.........######.........',
    '.......##wwwwww##.......',
    '......#wwmmmmmmww#......',
    '.....#wwmmmmmmmmww#.....',
    '....#wwmmmmmmmmmmww#....',
    '...#wwmmmmmmmmmmmmww#...',
    '..#wwmmmmmmmmmmmmmmww#..',
    '..#wwmmmmmmmmmmmmmmww#..',
    '..#wwmmmmmmmmmmmmmmww#..',
    '..#wwmmmmmmmmmmmmmmww#..',
    '..#wwmmmmmmmmmmmmmmww#..',
    '..#wwmmmmmmmmmmmmmmww#..',
    '..#wwmmmmmmmmmmmmmmww#..',
    '...#wwmmmmmmmmmmmmww#...',
    '....#wwmmmmmmmmmmww#....',
    '.....#wwmmmmmmmmww#.....',
    '......#wwmmmmmmww#......',
    '.......##YYYYYY##.......',
    '.........######.........',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  'color-verde': [ // 58
    '........................',
    '.........######.........',
    '.......##wwwwww##.......',
    '......#wwvvvvvvww#......',
    '.....#wwvvvvvvvvww#.....',
    '....#wwvvvvvvvvvvww#....',
    '...#wwvvvvvvvvvvvvww#...',
    '..#wwvvvvvvvvvvvvvvww#..',
    '..#wwvvvvvvvvvvvvvvww#..',
    '..#wwvvvvvvvvvvvvvvww#..',
    '..#wwvvvvvvvvvvvvvvww#..',
    '..#wwvvvvvvvvvvvvvvww#..',
    '..#wwvvvvvvvvvvvvvvww#..',
    '..#wwvvvvvvvvvvvvvvww#..',
    '...#wwvvvvvvvvvvvvww#...',
    '....#wwvvvvvvvvvvww#....',
    '.....#wwvvvvvvvvww#.....',
    '......#wwvvvvvvww#......',
    '.......##VVVVVV##.......',
    '.........######.........',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  'color-morado': [ // 59
    '........................',
    '.........######.........',
    '.......##wwwwww##.......',
    '......#wwbbbbbbww#......',
    '.....#wwbbbbbbbbww#.....',
    '....#wwbbbbbbbbbbww#....',
    '...#wwbbbbbbbbbbbbww#...',
    '..#wwbbbbbbbbbbbbbbww#..',
    '..#wwbbbbbbbbbbbbbbww#..',
    '..#wwbbbbbbbbbbbbbbww#..',
    '..#wwbbbbbbbbbbbbbbww#..',
    '..#wwbbbbbbbbbbbbbbww#..',
    '..#wwbbbbbbbbbbbbbbww#..',
    '..#wwbbbbbbbbbbbbbbww#..',
    '...#wwbbbbbbbbbbbbww#...',
    '....#wwbbbbbbbbbbww#....',
    '.....#wwbbbbbbbbww#.....',
    '......#wwbbbbbbww#......',
    '.......##BBBBBB##.......',
    '.........######.........',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  'color-marron': [ // 60
    '........................',
    '.........######.........',
    '.......##wwwwww##.......',
    '......#wwnnnnnnww#......',
    '.....#wwnnnnnnnnww#.....',
    '....#wwnnnnnnnnnnww#....',
    '...#wwnnnnnnnnnnnnww#...',
    '..#wwnnnnnnnnnnnnnnww#..',
    '..#wwnnnnnnnnnnnnnnww#..',
    '..#wwnnnnnnnnnnnnnnww#..',
    '..#wwnnnnnnnnnnnnnnww#..',
    '..#wwnnnnnnnnnnnnnnww#..',
    '..#wwnnnnnnnnnnnnnnww#..',
    '..#wwnnnnnnnnnnnnnnww#..',
    '...#wwnnnnnnnnnnnnww#...',
    '....#wwnnnnnnnnnnww#....',
    '.....#wwnnnnnnnnww#.....',
    '......#wwnnnnnnww#......',
    '.......##DDDDDD##.......',
    '.........######.........',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  pie: [ // 61
    '........................',
    '........................',
    '.....#p#.#p#.#p#........',
    '....#pp##pp##pp#.#p#....',
    '...#ppp##pp##pp##pp#....',
    '..#pppppppppppppppp#....',
    '..#pppppppppppppppp#....',
    '..#pppppppppppppppp#....',
    '...#ppppppppppppppp#....',
    '....#pppppppppppppp#....',
    '.....#ppppppppppppp#....',
    '......#pppppppppppp#....',
    '.......#ppppppppppp#....',
    '.......#pppppppppp#.....',
    '........#ppppppppp#.....',
    '........#ppppppppp#.....',
    '.........#ppppppp#......',
    '..........#qqqqq#.......',
    '...........#####........',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  boca: [ // 62
    '........................',
    '........................',
    '........................',
    '........................',
    '........########........',
    '......##rrrrrrrr##......',
    '....##rrrrrrrrrrrr##....',
    '..##rrrrrrrrrrrrrrrr##..',
    '.#rrrr#wwwwwwwwww#rrrr#.',
    '#rrrr#wwwwwwwwwwww#rrrr#',
    '#rrrr#wwwwwwwwwwww#rrrr#',
    '#rrrr#ww#PPPPPP#ww#rrrr#',
    '#rrrr#ww#PPPPPP#ww#rrrr#',
    '.#rrrr#w#PPPPPP#w#rrrr#.',
    '..##rrr##########rrr##..',
    '....##rrrrrrrrrrrr##....',
    '......##RRRRRRRR##......',
    '........########........',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  ojo: [ // 63
    '........................',
    '........................',
    '.........######.........',
    '......###cccccc###......',
    '....##cccccccccc##......',
    '...#cccccccccccccc#.....',
    '..#ccctttttttttcccc#....',
    '.#cccttttaaakkttcccc#...',
    '.#ccttttaawwkkttccccc#..',
    '#cctttttaawwkktttccccc#.',
    '#cctttttaaakkttttccccc#.',
    '#ccttttttttttttttccccc#.',
    '.#ccttttttttttttccccc#..',
    '.#cccttttttttttccccc#...',
    '..#cccctttttttccccc#....',
    '...#cccccccccccccc#.....',
    '....##CCCCCCCCCC##......',
    '......###CCCCCC###......',
    '.........######.........',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  rodilla: [ // 64
    '........................',
    '.........######.........',
    '.......##pppppp##.......',
    '......#pppppppppp#......',
    '.....#pppppppppppp#.....',
    '....#pppppppppppppp#....',
    '...#pppppppppppppppp#...',
    '..#pppppppppppppppppp#..',
    '..#pppp##tttttt##pppp#..',
    '..#ppp#ttccccccct#ppp#..',
    '..#ppp#ttcttttcct#ppp#..',
    '..#ppp#ttcttttcct#ppp#..',
    '..#ppp#ttccccccct#ppp#..',
    '..#pppp##tttttt##pppp#..',
    '..#pppppppppppppppppp#..',
    '...#pppppppppppppppp#...',
    '....#pppppppppppppp#....',
    '.....#pppppppppppp#.....',
    '......#qqqqqqqqqq#......',
    '.......##qqqqqq##.......',
    '.........######.........',
    '........................',
    '........................',
    '........................',
  ],
  codo: [ // 65
    '........................',
    '........................',
    '..######................',
    '..#pppp#................',
    '..#pppp#........#####...',
    '..#pppp#.......#ppppp#..',
    '..#pppp#......#pOpOpp#..',
    '..#pppp#......#ppppppp#.',
    '..#pppp#......#pOpOppp#.',
    '..#pppp#......#pppppp#..',
    '..#pppp#.....#pppppp#...',
    '..#pppp#....#pppppp#....',
    '..#pppp#...#pppppp#.....',
    '..#pppppO##pppppp#......',
    '..#pppppppppppp#........',
    '..#ppppppppppp#.........',
    '..#pppppppppp#..........',
    '..#OOOOOOOOOO#..........',
    '..#OOOOOOOOOO#..........',
    '...#OOOOOOOO#...........',
    '....########............',
    '........................',
    '........................',
    '........................',
  ],
};

// ============================================================================
// Las 9 insignias de gamificación (ValeriaPixelAwards.tsx)
//
// Cada insignia es un glifo de 24×24 en blanco y negro (caracteres '#' y 'a')
// con núcleo opcional ('b'). El componente dibuja el metal aplicando el tono
// del rango a 'a', el del núcleo a 'b' y el del fondo del panel a la placa.
//
// El ORDEN de los dos arrays es el que viaja en AWARD(glifo + rango<<8). Igual
// que los pictogramas: se añade al final, no se reordena.

/** Los 9 glifos, EN ORDEN DE ÍNDICE. */
export const AWARD_GLYPH_KEYS = [
  'flame',      // 0
  'paw',        // 1
  'star',       // 2
  'sunrise',    // 3
  'moon',       // 4
  'home',       // 5
  'yarn',       // 6
  'heart',      // 7
  'crown',      // 8
] as const;

export type PixelAwardGlyph = (typeof AWARD_GLYPH_KEYS)[number];

export const AWARD_TIER_KEYS = ['bronze', 'silver', 'gold', 'teal', 'violet'] as const;

export type PixelAwardTier = (typeof AWARD_TIER_KEYS)[number];

export interface PixelTierPalette { a: string; b: string; bg: string; }

/** Fondo OSCURO: es lo que hace que el metal se lea en un panel de 240. */
export const PIXEL_TIERS: Record<PixelAwardTier, PixelTierPalette> = {
  bronze: { bg: '#2b1e16', a: '#cd7f32', b: '#e8a760' },
  silver: { bg: '#1c2430', a: '#c0c8d8', b: '#ffffff' },
  gold:   { bg: '#2e2008', a: '#ffc400', b: '#ffea78' },
  teal:   { bg: '#0e2830', a: '#00e5ff', b: '#d0ffff' }, // «Diamante» en el firmware
  violet: { bg: '#280e30', a: '#ff2a6d', b: '#ffb8d2' }, // «Rubí» en el firmware
};

/**
 * Núcleo fijo de algunos glifos: el corazón de una llama es naranja aunque la
 * insignia sea de bronce. Sin esto, una llama de bronce es marrón sobre marrón.
 */
export const PIXEL_GLYPH_CORE: Record<PixelAwardGlyph, string> = {
  flame: '#ff8800',   // Cascabel fonador (núcleo sonoro cálido)
  paw: '#fca070',     // Huella de exploradora (almohadilla melocotón)
  star: '#00c4be',    // Orejitas atentas (ondas auditivas cristalinas)
  sunrise: '#00c4be', // Lupa / farol curioso (lente cristalina)
  moon: '#ffdc00',    // Lúa soñadora (luna dorada)
  home: '#8b5a2b',    // Mochila de palabras (cuero cálido)
  yarn: '#9b51e0',    // Ovillo de cuentos (hebra violeta)
  heart: '#e62828',   // Ronroneo afectivo (corazón carmín)
  crown: '#ffdc00',   // Corona de sabiduría lunar (oro brillante)
};

export const AWARD_GLYPHS: Record<PixelAwardGlyph, readonly string[]> = {
  flame: [ // 0
    '........................',
    '..........####..........',
    '.........#aaaa#.........',
    '........#aaaaaa#........',
    '.......#aaawwaaa#.......',
    '......#aaawwwwaaa#......',
    '.....#aaawwwwwwaaa#.....',
    '....#aaawwwwwwwwaaa#....',
    '...#aaawwwwwwwwwwaaa#...',
    '..#aaawwww#bb#wwwwaaa#..',
    '..#aaawww#bbbb#wwwaaa#..',
    '.#aaawww#bbbbbb#wwwaaa#.',
    '.#aaawww#bbbbbb#wwwaaa#.',
    '#aaawwww#bbbbbb#wwwwaaa#',
    '#aaawwww#bbbbbb#wwwwaaa#',
    '.#aaawww#bbbbbb#wwwaaa#.',
    '..#aaawww#bbbb#wwwaaa#..',
    '...#aaawww####wwwaaa#...',
    '....#aaawwwwwwwwaaa#....',
    '.....#aaawwwwwwaaa#.....',
    '......##aaaaaaaa##......',
    '........########........',
    '........................',
    '........................',
  ],
  paw: [ // 1
    '........................',
    '..........####..........',
    '.........#aaaa#.........',
    '........#aabbba#........',
    '...##...#aabbba#...##...',
    '..#aa#..#aabbba#..#aa#..',
    '.#abb#...#aaaa#...#bba#.',
    '.#abba#...####...#abba#.',
    '..#aa#............#aa#..',
    '...##..............##...',
    '........................',
    '.......##########.......',
    '.....##aaaaaaaaaa##.....',
    '....#aaaaaaaaaaaaaa#....',
    '...#aaaaabbbbbaaaaaa#...',
    '..#aaaaabbbbbbbaaaaaa#..',
    '..#aaaabbbbbbbbbaaaaa#..',
    '..#aaaabbbbbbbbbaaaaa#..',
    '...#aaaabbbbbbbaaaaa#...',
    '....#aaaabbbbbaaaaa#....',
    '.....##aaaaaaaaaa##.....',
    '.......##########.......',
    '........................',
    '........................',
  ],
  star: [ // 2
    '..##................##..',
    '.#aa#..###....###..#aa#.',
    '.#bba##aaa#..#aaa##abb#.',
    '..#bbaaaaa####aaaaabb#..',
    '...#aaaaaaaaaaaaaaab#...',
    '....#aaaaabbbbaaaaa#....',
    '..##aaaaaaaaaaaaaaaa##..',
    '.#aaaaaaaaaaaaaaaaaaaa#.',
    '..#aaaaaaaaaaaaaaaaaa#..',
    '....#aaaaabbbbaaaaa#....',
    '.....#aaaaaaaaaaaa#.....',
    '....#aaaaaaaaaaaaaa#....',
    '...#aaaaaaaaaaaaaaaa#...',
    '..#aaaaa#aaaaaa#aaaaa#..',
    '..#aaaa#aa#aa#aa#aaaa#..',
    '...#aa#aaa#aa#aaa#aa#...',
    '....##aaaa####aaaa##....',
    '......#aa#....#aa#......',
    '.......##......##.......',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  sunrise: [ // 3
    '.........######.........',
    '.......##aaaaaa##.......',
    '......#aaaaaaaaaa#..##..',
    '.....#aaaabbbbaaaa##aa#.',
    '....#aaaabbbbbbaaaa##...',
    '....#aaabbbbbbbbaaa#....',
    '...#aaabbbbbbbbbbaaa#...',
    '...#aaabbbbbbbbbbaaa#...',
    '...#aaabbbbbbbbbbaaa#...',
    '....#aaabbbbbbbbaaa#....',
    '....#aaaabbbbbbaaaa#....',
    '.....#aaaabbbbaaaa#m#...',
    '......#aaaaaaaaaa##mm#..',
    '.......##aaaaaa####.##..',
    '.........######..#nn#...',
    '..................#nn#..',
    '...................#nn#.',
    '....................#N#.',
    '.....................##.',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  moon: [ // 4
    '..............#####.....',
    '............##aaaaa#....',
    '...........#aaabbba#....',
    '..........#aaabbba##....',
    '.........#aaabbba#......',
    '..###...#aaabbba#.......',
    '.#aaa#.#aaabbba#........',
    '#aabbbaaaabbba#.........',
    '#a#b#aaaabbba#..........',
    '#aabbbaabbba#...........',
    '.#aaa#aabbba#...........',
    '..###abbba##............',
    '...#abbba#..###.........',
    '...#aabbba#.#aaa#.......',
    '..#aaabbba#..#..........',
    '.#aaaaabbba##...........',
    '#aaaaaaaabbb#####.......',
    '#aaaaaaaaabbbbbbb#......',
    '.#aaaaaaaaaaabbba#......',
    '..##aaaaaaaaabb##.......',
    '....###aaaaaa##.........',
    '.......######...........',
    '........................',
    '........................',
  ],
  home: [ // 5
    '.........######.........',
    '........#aaaaaa#........',
    '.......#a######a#.......',
    '......#aaaaaaaaaa#......',
    '.....#aaaaaaaaaaaa#.....',
    '....################....',
    '...#aaaaaaaaaaaaaaaa#...',
    '..#aaaaaaaaaaaaaaaaaa#..',
    '..#aa##############aa#..',
    '..#aa#bbbbbbbbbbbb#aa#..',
    '..#aa#bbbbbbbbbbbb#aa#..',
    '..#aa#bbbb#ww#bbbb#aa#..',
    '..#aa#bbbb#ww#bbbb#aa#..',
    '..#aa#bbbb####bbbb#aa#..',
    '..#aa#bbbbbbbbbbbb#aa#..',
    '..#aa##############aa#..',
    '..#aaaaaaaaaaaaaaaaaa#..',
    '..#aaaaaa######aaaaaa#..',
    '..#aaaaaa#bbbb#aaaaaa#..',
    '..#aaaaaa#bbbb#aaaaaa#..',
    '..#aaaaaa######aaaaaa#..',
    '...##################...',
    '........................',
    '........................',
  ],
  yarn: [ // 6
    '.........######.........',
    '......###aaaaaa###......',
    '....##aaaaaaaaaaaa##....',
    '...#aaaa##aaaa##aaaa#...',
    '..#aaaa#bb#aa#bb#aaaa#..',
    '.#aaaaaa##aaaa##aaaaaa#.',
    '.#aa##aaaaaaaaaaaa##aa#.',
    '#aa#bb#aaaa##aaaa#bb#aa#',
    '#aaa##aaaa#bb#aaaa##aaa#',
    '#aaaaaaaaaa##aaaaaaaaaa#',
    '#aaaaaa##aaaaaa##aaaaaa#',
    '#aaa###bb#aaaa#bb#aaaaa#',
    '.#aa#bb##aaaaaa##aaaaa#.',
    '.#aaa##aaaaaaaaaaaaaaa#.',
    '..#aaaaaaaaaaaaaaaaaa#..',
    '...#aaaaaaaaaaaaaaaa#...',
    '....##aaaaaaaaaaaa##....',
    '......###aaaaaa###......',
    '.........######.........',
    '...............#a#......',
    '................#aa#....',
    '.................#aaa#..',
    '...................##...',
    '........................',
  ],
  heart: [ // 7
    '....######....######....',
    '..##aaaaaa##..##aaaa##..',
    '.#aaaaaaaaaa##aaaaaaaa#.',
    '#aaaaaaaaaaaaaaaaaaaaaa#',
    '#aaaaaaaaaaaaaaaaaaaaaa#',
    '#aaaa#bbbb#aa#bbbb#aaaa#',
    '#aaa#bbggbb##bbggbb#aaa#',
    '#aaa#b#gg#b##b#gg#b#aaa#',
    '#aaa#bbggbb##bbggbb#aaa#',
    '#aaaa#bbbb#aa#bbbb#aaaa#',
    '#aaaaa####aaaa####aaaaa#',
    '.#aaaaaaaa#gg#aaaaaaaa#.',
    '.#aaaaaaa#gggg#aaaaaaa#.',
    '..#aaaaaa#gggg#aaaaaa#..',
    '..#aaaaaaa####aaaaaaa#..',
    '...#aaaaaaaaaaaaaaaa#...',
    '....#aaaaaaaaaaaaaa#....',
    '.....#aaaaaaaaaaaa#.....',
    '......#aaaaaaaaaa#......',
    '.......#aaaaaaaa#.......',
    '........#aaaaaa#........',
    '.........#aaaa#.........',
    '..........#aa#..........',
    '...........##...........',
  ],
  crown: [ // 8
    '..##........##........##',
    '.#bb#......#bb#......#bb',
    '..##........##........##',
    '..#aa#....#aaaa#....#aa#',
    '..#aaa#..#aaaaaa#..#aaa#',
    '..#aaaa##aaaaaaaa##aaaa#',
    '..#aaaaaaaaaaaaaaaaaaaa#',
    '..#aaaaaaaa#bb#aaaaaaaa#',
    '..#aaaaaaa#bbbb#aaaaaaa#',
    '..#aaaaaaa#bbbb#aaaaaaa#',
    '..#aa#bb#aa#bb#aa#bb#aa#',
    '..#aa#bb#aa####aa#bb#aa#',
    '..#aaaaaaaaaaaaaaaaaaaa#',
    '..#aaaaaaaaaaaaaaaaaaaa#',
    '..####################..',
    '..#aaaaaaaaaaaaaaaaaa#..',
    '..#a#bb#aa#bb#aa#bb#a#..',
    '..#aaaaaaaaaaaaaaaaaa#..',
    '..####################..',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
};
